### ISSUE TITLE
500 server error when requesting balance/<address> when address has no balance

### ISSUE THREAD

**Issue by pitersky** [CityOfZion/dora-sdk-ts#5]
example:

curl -v 'https://dora.coz.io/api/v1/neo3/testnet/balance/NXx9xwpH5tmAjsqbTyfZqFnQd74ME2eat5'

answer:
...
< HTTP/2 500
...
'NoneType' object has no attribute 'keys'

**Comment by Zidious** [comment]
I am not getting any errors, is this still an issue?
